wxsheet: wxsheet.cc
	g++ -O2 -o wxsheet wxsheet.cc `wx-config --cxxflags --libs`

#g++ -o wxsheet.exe wxsheet.cc -s -W -Wall -mwindows -mthreads -DHAVE_W32API_H -D__WXMSW__ -IC:\MinGWStudio\Include -IC:\MinGWStudio\Include\msw -LC:\MinGWStudio\lib -lwxmsw26_core -lwxmsw26_adv -lwxbase26 -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32
